# Use postgres/example user/password credentials
version: '3.9'

services:
  protein-backend:
    container_name: protein-backend
    build: ./next-protein-backend-main
    expose:
      - 5000
    env_file:
      - ./next-protein-backend-main/.production.env
    volumes:
      - ./next-protein-backend-main:/srv/app/next-protein-backend
    ports:
      - "5000:5000"
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

#  protein-frontend:
#    container_name: protein-frontend
#    build: ./next-protein-frontend-main
#    environment:
#      - REACT_APP_PORT=3000
#    expose:
#      - 3000
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./next-protein-frontend-main:/srv/app/next-protein-frontend
#    links:
#      - protein-backend
#    command: npm run dev

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_DB: protein
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kehxbrKEHXBR1!
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

